package org.apache.asterix.connector.example

/**
 * Created by MingdaLi on 1/4/17.
 */
object TPCSchemas {
  //  case class StoreSales(ss_sold_date_sk: Int,
  //  ss_sold_time_sk: Int,
  //  ss_item_sk: Int,
  //  ss_customer_sk: Int,
  //  ss_cdemo_sk: Int,
  //  ss_hdemo_sk: Int,
  //  ss_addr_sk: Int,
  //  ss_store_sk: Int,
  //  ss_promo_sk: Int,
  //  ss_ticket_number: Int,
  //  ss_quantity: Int,
  //  ss_wholesale_cost: Float,
  //  ss_list_price: Float,
  //  ss_sales_price: Float,
  //  ss_ext_discount_amt: Float,
  //  ss_ext_sales_price: Float,
  //  ss_ext_wholesale_cost: Float,
  //  ss_ext_list_price: Float,
  //  ss_ext_tax: Float,
  //  ss_coupon_amt: Float,
  //  ss_net_paid: Float,
  //  ss_net_paid_inc_tax: Float,
  //  ss_net_profit: Float)
  //  case class StoreReturns(sr_returned_date_sk: Int,
  //  sr_return_time_sk: Int,
  //  sr_item_sk: Int,
  //  sr_customer_sk: Int,
  //  sr_cdemo_sk: Int,
  //  sr_hdemo_sk: Int,
  //  sr_addr_sk: Int,
  //  sr_store_sk: Int,
  //  sr_reason_sk: Int,
  //  sr_ticket_number: Int,
  //  sr_return_quantity: Int,
  //  sr_return_amt: Float,
  //  sr_return_tax: Float,
  //  sr_return_amt_inc_tax: Float,
  //  sr_fee: Float,
  //  sr_return_ship_cost: Float,
  //  sr_refunded_cash: Float,
  //  sr_reversed_charge: Float,
  //  sr_store_credit: Float,
  //  sr_net_loss: Float)
  //  case class Store(s_store_sk: Int,
  //  s_store_id: String,
  //  s_rec_start_date: String,
  //  s_rec_end_date: String,
  //  s_closed_date_sk: Int,
  //  s_store_name: String,
  //  s_number_employees: Int,
  //  s_floor_space: Int,
  //  s_hours: String,
  //  s_manager: String,
  //  s_market_id: Int,
  //  s_geography_class: String,
  //  s_market_desc: String,
  //  s_market_manager: String,
  //  s_division_id: Int,
  //  s_division_name: String,
  //  s_company_id: Int,
  //  s_company_name: String,
  //  s_street_number: String,
  //  s_street_name: String,
  //  s_street_type: String,
  //  s_suite_number: String,
  //  s_city: String,
  //  s_county: String,
  //  s_state: String,
  //  s_zip: String,
  //  s_country: String,
  //  s_gmt_offset: Float,
  //  s_tax_precentage: Float)
  //  case class WebSales(ws_sold_date_sk: Int,
  //  ws_sold_time_sk: Int,
  //  ws_ship_date_sk: Int,
  //  ws_item_sk: Int,
  //  ws_bill_customer_sk: Int,
  //  ws_bill_cdemo_sk: Int,
  //  ws_bill_hdemo_sk: Int,
  //  ws_bill_addr_sk: Int,
  //  ws_ship_customer_sk: Int,
  //  ws_ship_cdemo_sk: Int,
  //  ws_ship_hdemo_sk: Int,
  //  ws_ship_addr_sk: Int,
  //  ws_web_page_sk: Int,
  //  ws_web_site_sk: Int,
  //  ws_ship_mode_sk: Int,
  //  ws_warehouse_sk: Int,
  //  ws_promo_sk: Int,
  //  ws_order_number: Int,
  //  ws_quantity: Int,
  //  ws_wholesale_cost: Float,
  //  ws_list_price: Float,
  //  ws_sales_price: Float,
  //  ws_ext_discount_amt: Float,
  //  ws_ext_sales_price: Float,
  //  ws_ext_wholesale_cost: Float,
  //  ws_ext_list_price: Float,
  //  ws_ext_tax: Float,
  //  ws_coupon_amt: Float,
  //  ws_ext_ship_cost: Float,
  //  ws_net_paid: Float,
  //  ws_net_paid_inc_tax: Float,
  //  ws_net_paid_inc_ship: Float,
  //  ws_net_paid_inc_ship_tax: Float,
  //  ws_net_profit: Float)
  //  case class Item(i_item_sk: Int,
  //                  i_item_id: String,
  //                  i_rec_start_date: String,
  //                  i_rec_end_date: String,
  //                  i_item_desc: String,
  //                  i_current_price: Float,
  //                  i_wholesale_cost: Float,
  //                  i_brand_id: Int,
  //                  i_brand: String,
  //                  i_class_id: Int,
  //                  i_class: String,
  //                  i_category_id: Int,
  //                  i_category: String,
  //                  i_manufact_id: Int,
  //                  i_manufact: String,
  //                  i_size: String,
  //                  i_formulation: String,
  //                  i_color: String,
  //                  i_units: String,
  //                  i_container: String,
  //                  i_manager_id: Int,
  //                  i_product_name: String)
  //  case class Promotion(p_promo_sk: Int,
  //  p_promo_id: String,
  //  p_start_date_sk: Int,
  //  p_end_date_sk: Int,
  //  p_item_sk: Int,
  //  p_cost: Float,
  //  p_response_target: Int,
  //  p_promo_name: String,
  //  p_channel_dmail: String,
  //  p_channel_email: String,
  //  p_channel_catalog: String,
  //  p_channel_tv: String,
  //  p_channel_radio: String,
  //  p_channel_press: String,
  //  p_channel_event: String,
  //  p_channel_demo: String,
  //  p_channel_details: String,
  //  p_purpose: String,
  //  p_discount_active: String)
  case class StoreSales(ss_sold_date_sk: String,
                        ss_sold_time_sk: String,
                        ss_item_sk: String, //2
                        ss_customer_sk: String,//3
                        ss_cdemo_sk: String,
                        ss_hdemo_sk: String,
                        ss_addr_sk: String,
                        ss_store_sk: String,
                        ss_promo_sk: String,
                        ss_ticket_number: String//9
                        //                        ss_quantity: String,
                        //                        ss_wholesale_cost: String,
                        //                        ss_list_price: String,
                        //                        ss_sales_price: String,
                        //                        ss_ext_discount_amt: String,
                        //                        ss_ext_sales_price: String,
                        //                        ss_ext_wholesale_cost: String,
                        //                        ss_ext_list_price: String,
                        //                        ss_ext_tax: String,
                        //                        ss_coupon_amt: String,
                        //                        ss_net_paid: String
                        //                      ss_net_paid_inc_tax: String,
                        //                      ss_net_profit: String
                         )
  case class StoreReturns(sr_returned_date_sk: String,
                          sr_return_time_sk: String,
                          sr_item_sk: String, //2
                          sr_customer_sk: String, //3
                          sr_cdemo_sk: String,
                          sr_hdemo_sk: String,
                          sr_addr_sk: String,
                          sr_store_sk: String,
                          sr_reason_sk: String,
                          sr_ticket_number: String //9
                          //                          sr_return_quantity: String,
                          //                          sr_return_amt: String,
                          //                          sr_return_tax: String,
                          //                          sr_return_amt_inc_tax: String,
                          //                          sr_fee: String,
                          //                          sr_return_ship_cost: String,
                          //                          sr_refunded_cash: String,
                          //                          sr_reversed_charge: String,
                          //                          sr_store_credit: String,
                          //                          sr_net_loss: String
                           )
  case class Store(s_store_sk: String, //0
                   s_store_id: String,
                   s_rec_start_date: String,
                   s_rec_end_date: String,
                   s_closed_date_sk: String,
                   s_store_name: String,//5
                   //                   s_number_employees: String,
                   //                   s_floor_space: String,
                   //                   s_hours: String,
                   //                   s_manager: String,
                   //                   s_market_id: String,
                   //                   s_geography_class: String,
                   //                   s_market_desc: String,
                   //                   s_market_manager: String,
                   s_division_id: String,
                   s_division_name: String,
                   s_company_id: String,
                   s_company_name: String,//17
                   s_street_number: String,//18
                   s_street_name: String,
                   s_street_type: String,
                   s_suite_number: String,
                   s_city: String,
                   s_county: String,
                   s_state: String, //24
                   s_zip: String//25
                   //                   s_country: String,
                   //                   s_gmt_offset: String,
                   //                   s_tax_precentage: String
                    )
  case class WebSales(ws_sold_date_sk: String,
                      ws_sold_time_sk: String,
                      ws_ship_date_sk: String,
                      ws_item_sk: String,
                      ws_bill_customer_sk: String,
                      ws_bill_cdemo_sk: String,
                      ws_bill_hdemo_sk: String,
                      ws_bill_addr_sk: String,
                      ws_ship_customer_sk: String,
                      ws_ship_cdemo_sk: String,
                      ws_ship_hdemo_sk: String,
                      ws_ship_addr_sk: String,
                      ws_web_page_sk: String,
                      ws_web_site_sk: String,
                      ws_ship_mode_sk: String,
                      ws_warehouse_sk: String,
                      ws_promo_sk: String,
                      ws_order_number: String,
                      ws_quantity: String,
                      ws_wholesale_cost: String,
                      ws_list_price: String
                      //                      ws_sales_price: String,
                      //                      ws_ext_discount_amt: String,
                      //                      ws_ext_sales_price: String,
                      //                      ws_ext_wholesale_cost: String,
                      //                      ws_ext_list_price: String,
                      //                      ws_ext_tax: String,
                      //                      ws_coupon_amt: String,
                      //                      ws_ext_ship_cost: String,
                      //                      ws_net_paid: String,
                      //                      ws_net_paid_inc_tax: String,
                      //                      ws_net_paid_inc_ship: String,
                      //                      ws_net_paid_inc_ship_tax: String,
                      //                      ws_net_profit: String
                       )
  case class CatalogSales(cs_sold_date_sk: String,
                          cs_sold_time_sk: String,
                          cs_ship_date_sk: String,
                          cs_bill_customer_sk: String,//3
                          cs_bill_cdemo_sk: String,
                          cs_bill_hdemo_sk: String,
                          cs_bill_addr_sk: String,
                          cs_ship_customer_sk: String,
                          cs_ship_cdemo_sk: String,
                          cs_ship_hdemo_sk: String,
                          cs_ship_addr_sk: String,
                          cs_call_center_sk: String,
                          cs_catalog_page_sk: String,
                          cs_ship_mode_sk: String,
                          cs_warehouse_sk: String,
                          cs_item_sk: String,//15
                          cs_promo_sk: String,
                          cs_order_number: String,//17
                          cs_quantity: String,
                          cs_wholesale_cost: String
                          //  cs_list_price: String,
                          //  cs_sales_price: String,
                          //  cs_ext_discount_amt: String,
                          //  cs_ext_sales_price: String,
                          //  cs_ext_wholesale_cost: String,
                          //  cs_ext_list_price: String,
                          //  cs_ext_tax: String,
                          //  cs_coupon_amt: String,
                          //  cs_ext_ship_cost: String,
                          //  cs_net_paid: String,
                          //  cs_net_paid_inc_tax: String,
                          //  cs_net_paid_inc_ship: String,
                          //  cs_net_paid_inc_ship_tax: String,
                          //  cs_net_profit: String,
                           )
  case class CatalogReturns(cr_returned_date_sk: String,
                            cr_return_time_sk: String,
                            cr_item_sk: String,//2
                            cr_refunded_customer_sk: String,
                            cr_refunded_cdemo_sk: String,
                            cr_refunded_hdemo_sk: String,
                            cr_refunded_addr_sk: String,
                            cr_returning_customer_sk: String,
                            cr_returning_cdemo_sk: String,
                            cr_returning_hdemo_sk: String,
                            cr_returning_addr_sk: String,
                            cr_call_center_sk:String,
                            cr_catalog_page_sk: String,
                            cr_ship_mode_sk: String,
                            cr_warehouse_sk: String,
                            cr_reason_sk: String,
                            cr_order_number: String//16
                            //                            cr_return_quantity: String,
                            //                            cr_return_amount: String,
                            //                            cr_return_tax: String,
                            //                            cr_return_amt_inc_tax: String,
                            //                            cr_fee: String,
                            //                            cr_return_ship_cost: String,
                            //                            cr_refunded_cash: String,
                            //                            cr_reversed_charge: String,
                            //                            cr_store_credit: String,
                            //                            cr_net_loss: String
                             )
  case class Item(i_item_sk: String,
                  i_item_id: String,
                  i_rec_start_date: String,
                  i_rec_end_date: String,
                  i_item_desc: String,
                  i_current_price: String,
                  i_wholesale_cost: String,//6
                  i_brand_id: String,
                  i_brand: String,
                  //                  i_class_id: String,
                  //                  i_class: String,
                  //                  i_category_id: String,
                  //                  i_category: String,
                  i_manufact_id: String,
                  //                                    i_manufact: String,
                  i_size: String,//15
                  //                  i_formulation: String,
                  i_color: String,
                  i_units: String,
                  //                  i_container: String,
                  i_manager_id: String,
                  i_product_name: String )//21
  case class Promotion(p_promo_sk: String,
                       p_promo_id: String,
                       p_start_date_sk: String,
                       p_end_date_sk: String,
                       p_item_sk: String,
                       p_cost: String,
                       p_response_target: String,
                       p_promo_name: String,
                       p_channel_dmail: String,
                       p_channel_email: String,
                       p_channel_catalog: String,
                       p_channel_tv: String,
                       p_channel_radio: String,
                       p_channel_press: String,
                       p_channel_event: String,
                       p_channel_demo: String,
                       p_channel_details: String,
                       p_purpose: String,
                       p_discount_active: String
                        )
  case class Inventory(inv_date_sk: String,
                       inv_item_sk: String,
                       inv_warehouse_sk: String,
                       inv_quantity_on_hand: String
                        )
  case class Data_dim( d_date_sk: String,// 0
                       d_date_id: String,
                       d_date: String,
                       d_month_seq: String,
                       d_week_seq: String,
                       d_quarter_seq: String,
                       d_year: String,
                       d_dow: String,
                       d_moy: String,
                       d_dom: String,
                       d_qoy: String,
                       d_fy_year: String,
                       d_fy_quarter_seq: String,
                       d_fy_week_seq: String,
                       d_day_name: String,
                       d_quarter_name: String) //15
  case class Warehouse( w_warehouse_sk: String,//0
                        w_warehouse_id: String,
                        w_warehouse_name: String,
                        w_warehouse_sq_ft: String
                        //                        w_street_number: String,
                        //                        w_street_name: String,
                        //                        w_street_type: String,
                        //                        w_suite_number: String,
                        //                        w_city: String,
                        //                        w_county: String,
                        //                        w_state: String,
                        //                        w_zip: String,
                        //                        w_country: String,
                        //                        w_gmt_offset: String
                        )
  case class Customer_demographics( cd_demo_sk: String,//0
                                    cd_gender: String,
                                    cd_marital_status: String,
                                    cd_education_status: String,
                                    cd_purchase_estimate: String,
                                    cd_credit_rating: String,
                                    cd_dep_count: String,
                                    cd_dep_employed_count: String,
                                    cd_dep_college_count: String)
  case class Household_demographics( hd_demo_sk: String,//0
                                     hd_income_band_sk: String,
                                     hd_buy_potential: String,
                                     hd_dep_count: String,
                                     hd_vehicle_count: String)
  case class Customer( c_customer_sk: String,// 0
                       c_customer_id: String,
                       c_current_cdemo_sk: String,
                       c_current_hdemo_sk: String,
                       c_current_addr_sk: String,
                       c_first_shipto_date_sk: String,
                       c_first_sales_date_sk: String,
                       c_salutation: String,
                       c_first_name: String,
                       c_last_name: String,
                       c_preferred_cust_flag: String,
                       c_birth_day: String,
                       c_birth_month: String,
                       c_birth_year: String,
                       c_birth_country: String,
                       c_login: String//15
                       //                       c_email_address: String,
                       //                       c_last_review_date_sk: String
                       )
  case class Customer_address( ca_address_sk: String,// 0
                               ca_address_id: String,
                               ca_street_number: String,
                               ca_street_name: String,
                               ca_street_type: String,
                               ca_suite_number: String,
                               ca_city: String,
                               ca_county: String,
                               ca_state: String,
                               ca_zip: String,
                               ca_country: String,
                               ca_gmt_offset: String,
                               ca_location_type: String) //12

  def broadcast(table: String, scaleFactor: Int): Boolean = {
    table match {
      case "dd" => true
      case "cs" => false
      case "i" => if(scaleFactor < 4) true
        false
      case "s" => true
      case "sr" => false
      case "ss" => false
      case "c" => false
      case "ca" => false
    }
  }

}
